#spring.application.name=springbootprac
# DataSource Config
spring:
  application:
    name: springbootprac
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/user_data
server:
  port: 8080